---

name: "container-test"

trigger: none

variables:
  containerImage: "ubuntu:20.04"

pool:
  name: 'vmss-agent-pool-linux-001'

resources:
  containers:
    - container: ubuntu20_04
      image: '${{ variables.containerImage }}'

jobs:
  - job: test
    displayName: "Test Container Job"
    continueOnError: false
    container: ubuntu20_04

    steps:

      - checkout: self

      - script: |
          source /etc/os-release
          printf "Running on: %s\n" "$PRETTY_NAME"
        displayName: Check operating system version
