---

name: "container-test"

trigger: none

variables:
  containerImage: "ubuntu:20.04"

pool:
  name: 'vmss-agent-pool-linux-001'


resources:
  containers:
    - container: azure-tools
      image: '${{ variables.containerImage }}'
      # options: "--user 0:0 --name azure-tools"

jobs:
  - job: test
    displayName: "Test Container Job"
    continueOnError: false
    container: azure-tools

    steps:

      - checkout: self

      - script: |
          source /etc/os-release
          printf "Running on: %s\n" "$PRETTY_NAME"
        displayName: Check operating system version

