---

parameters:
  - name: azureSubscription
    type: string
  - name: container
    type: string
  - name: environmentName
    type: string
  - name: poolName
    type: string
  - name: terraformDirectory
    type: string

jobs:
  - deployment: terraform_apply
    # timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
    pool: ${{ parameters.poolName }}
    ${{ if gt(length(parameters.container),0) }}:
      container: ${{ parameters.container }}
    environment: ${{ parameters.environmentName }}
    strategy:
      runOnce:
        deploy:
          steps:

            - template: ../steps/terraform-apply.yml

            # - script: |
            #     env
            #     ls "$SYSTEM_DEFAULTWORKINGDIRECTORY"
            #   displayName: Debug
