---

parameters:
  - name: azureSubscription
    type: string
  - name: environmentName
    type: string
  - name: poolName
    type: string
  - name: terraformVersions
    type: string
    default: latest

jobs:
  - deployment: deployment
    # timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
    pool: ${{ parameters.poolName }}
    # ${{ if gt(length(parameters.container),0) }}:
    #   container: ${{ parameters.container }}
    environment: ${{ parameters.environmentName }}
    strategy:
      runOnce:
        deploy:
          steps:

            - script: |
                env
                ls "$SYSTEM_DEFAULTWORKINGDIRECTORY"
              displayName: Debug
