---

parameters:
  - name: checkout
    type: object
  - name: container
    type: string
  - name: poolName
    type: string
  - name: terraformVersion
    type: string
    default: 'latest'
  - name: terraformDirectory
    type: string
  - name: terraformTfVars
    type: object


jobs:
  - job: init
    pool: ${{ parameters.poolName }}
    ${{ if gt(length(parameters.container),0) }}:
      container: ${{ parameters.container }}
    steps:
      - template: ../steps/terraform-init.yml
        parameters:
          terraformVersion: ${{ parameters.terraformVersion }}
          checkout: ${{ parameters.checkout }}
          terraformDirectory: ${{ parameters.terraformDirectory }}
          terraformTfVars: ${{ parameters.terraformTfVars }}
