---

parameters:
  - name: terraformVersion
    type: string
    default: latest
  - name: checkout
    type: object


jobs:
  - job: init
    # TODO: template
    steps:
      - template: ../steps/terraform-init.yml
        parameters:
          terraformVersion: ${{ pararmeters.terraformVersion }}
          checkout: ${{ pararmeters.terraformVersion }}
