---

parameters:
  - name: azureSubscription
    type: string
  - name: checkout
    type: object
  - name: container
    type: string
  - name: destroyMode
    type: boolean
  - name: environmentName
    type: string
  - name: poolName
    type: string
  - name: terraformVersion
    type: string
    default: 'latest'
  - name: terraformDirectory
    type: string
  - name: terraformTfVars
    type: object


jobs:
  - job: init_plan
    workspace:
      clean: all
    pool: ${{ parameters.poolName }}
    ${{ if gt(length(parameters.container),0) }}:
      container: ${{ parameters.container }}

    steps:

      - template: ../steps/terraform-init.yml
        parameters:
          azureSubscription: ${{ parameters.azureSubscription }}
          environmentName: ${{ parameters.environmentName }}
          terraformVersion: ${{ parameters.terraformVersion }}
          checkout: ${{ parameters.checkout }}
          terraformDirectory: ${{ parameters.terraformDirectory }}
          terraformTfVars: ${{ parameters.terraformTfVars }}

      - template: ../steps/terraform-plan.yml
        parameters:
          azureSubscription: ${{ parameters.azureSubscription }}
          environmentName: ${{ parameters.environmentName }}
          destroyMode: ${{ parameters.destroyMode }}
          terraformDirectory: ${{ parameters.terraformDirectory }}
          terraformTfVars: ${{ parameters.terraformTfVars }}
