---

parameters:
  - name: terraformVersions
    type: string
    default: latest



jobs:
  - job: init
    steps:

      - checkout: self
      - checkout: git://$(project)/module

      - script: |
          env
          ls "$SYSTEM_DEFAULTWORKINGDIRECTORY"
        displayName: Debug

# - task: Bash@3
#   inputs:
#     filePath: 'test.sh'
#     arguments: 'arg1'
#     workingDirectory: '$(System.WorkingDirectory)/pipelines/terraform/scripts'
#     failOnStderr: true
#     bashEnvValue: 'tony=good'
