---

parameters:
  - name: azureSubscription
    type: string
  # - name: beStorageAccountName
  #   type: string
  # - name: beContainerName
  #   type: string
  # - name: beKey
  #   type: string
  # - name: beResourceGroupName
  #   type: string
  # - name: beSubscriptionId
  #   type: string
  - name: checkout
    type: object
  - name: container
    type: string
  - name: destroyMode
    type: boolean
  - name: destroyModeLocal
    type: boolean
  - name: environmentName
    type: string
  - name: environmentParameters
    type: object
  - name: poolName
    type: string
  - name: terraformDirectory
    type: string
  - name: terraformTfVars
    type: object
  - name: terraformVersion
    type: string


jobs:
  - job: init_plan
    workspace:
      clean: all
    pool: ${{ parameters.poolName }}
    ${{ if gt(length(parameters.container),0) }}:
      container: ${{ parameters.container }}

    steps:

      - template: ../steps/terraform-init.yml
        parameters:
          azureSubscription: ${{ parameters.azureSubscription }}
          # beStorageAccountName: ${{ parameters.beStorageAccountName }}
          # beContainerName: ${{ parameters.beContainerName }}
          # beKey: ${{ parameters.beKey }}
          # beResourceGroupName: ${{ parameters.beResourceGroupName }}
          # beSubscriptionId: ${{ parameters.beSubscriptionId }}
          destroyMode: ${{ parameters.destroyMode }}
          destroyModeLocal: ${{ parameters.destroyModeLocal }}
          environmentName: ${{ parameters.environmentName }}
          environmentParameters: ${{ parameters.environmentParameters }}
          checkout: ${{ parameters.checkout }}
          terraformDirectory: ${{ parameters.terraformDirectory }}
          terraformTfVars: ${{ parameters.terraformTfVars }}
          terraformVersion: ${{ parameters.terraformVersion }}

      - template: ../steps/terraform-plan.yml
        parameters:
          azureSubscription: ${{ parameters.azureSubscription }}
          environmentName: ${{ parameters.environmentName }}
          environmentParameters: ${{ parameters.environmentParameters }}
          destroyMode: ${{ parameters.destroyMode }}
          terraformDirectory: ${{ parameters.terraformDirectory }}
          terraformTfVars: ${{ parameters.terraformTfVars }}
