---

parameters:
  - name: terraformVersion
    type: string
    default: 'latest'
  - name: terraformDirectory
    type: string
  - name: checkout
    type: object


jobs:
  - job: init
    # TODO: template
    steps:
      - template: ../steps/terraform-init.yml
        parameters:
          terraformVersion: ${{ parameters.terraformVersion }}
          checkout: ${{ parameters.checkout }}
          terraformDirectory: ${{ parameters.terraformDirectory }}
