---

parameters:
  - name: azureSubscription
    type: string
    default: ''
  - name: container
    type: string
    default: ''
  - name: dependsOn
    type: object
    default: []
  - name: environments
    type: object
    default:
      - demo
  - name: environmentParameters
    type: object
    default:
      demo:
        dependsOn: []
        environmentName: "demo"
      dev:
        dependsOn: []
        environmentName: "dev"
      test:
        dependsOn: [dev]
        environmentName: "test"
      prod:
        dependsOn: [dev, test]
        environmentName: "prod"
  - name: initCheckout
    type: object
    default: []
  - name: poolName
    type: string
    default: 'Azure Pipelines'
  - name: stages
    type: object
    default:
      - init_plan
      - apply
  - name: stageParameters
    type: object
    default:
      init_plan:
        dependsOn: []
        # condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
        condition: succeeded()
        stageName: "init_plan"
      # plan:
      #   dependsOn: [init]
      #   # condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
      #   condition: succeeded()
      #   stageName: "plan"
      apply:
        dependsOn: [init_plan]
        # condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
        condition: succeeded()
        stageName: "apply"
      destroy:
        dependsOn: [init_plan]
        # condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
        condition: succeeded()
        stageName: "destroy"
  - name: terraformDirectory
    type: string
  - name: terraformTfVars
    type: object
    default: {}

stages:

  - template: stages/terraform-environments.yml
    parameters:
      azureSubscription: ${{ parameters.azureSubscription }}
      container: ${{ parameters.container }}
      environments: ${{ parameters.environments }}
      environmentParameters: ${{ parameters.environmentParameters }}
      dependsOn: ${{ parameters.dependsOn }}
      initCheckout: ${{ parameters.initCheckout }}
      stages: ${{ parameters.stages }}
      stageParameters: ${{ parameters.stageParameters }}
      poolName: ${{ parameters.poolName }}
      terraformDirectory: ${{ parameters.terraformDirectory }}
      terraformTfVars: ${{ parameters.terraformTfVars }}
