---

name: "container-test"

trigger: none

variables:
- group: build
- name: containerImage
  value: "ubuntu:22.04"

pool:
  name: 'vmss-agent-pool-linux-001'

resources:
  containers:
    - container: ubuntu20_04
      image: '${{ variables.containerImage }}'

jobs:
  - job: test
    displayName: "Test Container Job"
    continueOnError: false
    container: ubuntu20_04

    steps:

      - checkout: self

      - script: |
          env
        displayName: Show environment variables

      - script: |
          source /etc/os-release
          printf "Running on: %s\n" "$PRETTY_NAME"
        displayName: Check operating system version

      - script: |
          echo "Build index: $(build_index)"
        displayName: Check build index
