---

name: "container-test"

trigger: none

variables:
- group: build
- name: containerImage
  value: "ubuntu:22.04"

pool:
  name: 'vmss-agent-pool-linux-003'

jobs:
  - job: Build
    strategy:
      matrix:
        Python35:
          PYTHON_VERSION: '3.5'
        Python36:
          PYTHON_VERSION: '3.6'
        Python37:
          PYTHON_VERSION: '3.7'
      maxParallel: 3
    steps:

    - checkout: none

    - script: |
        echo $(PYTHON_VERSION)
        hostname
      displayName: Matrix output

    - script: |
        sudo apt update
        sudo apt install -y jq
        curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2021-02-01" | jq
      displayName: Get Instance Metadata Service
