---

parameters:
  # - name: azureSubscription
  #   type: string
  - name: container
    type: string
  - name: poolName
    type: string
  - name: environments
    type: object
  - name: environmentParameters
    type: object
  - name: dependsOn
    type: object
  - name: destroyMode
    type: boolean
  - name: destroyModeLocal
    type: boolean
  - name: initCheckout
    type: object
  - name: stages
    type: object
  - name: stageParameters
    type: object
  - name: terraformDirectory
    type: string
  - name: terraformTfVars
    type: object

stages:

  - ${{ each environment in parameters.environments }}:
    - template: ../stages/terraform-stages.yml
      parameters:
        azureSubscription: ${{ parameters.environmentParameters[environment].azureSubscription }}
        # beStorageAccountName: ${{ parameters.environmentParameters[environment].beStorageAccountName }}
        # beContainerName: ${{ parameters.environmentParameters[environment].beContainerName }}
        # beKey: ${{ parameters.environmentParameters[environment].beKey }}
        # beResourceGroupName: ${{ parameters.environmentParameters[environment].beResourceGroupName }}
        # beSubscriptionId: ${{ parameters.environmentParameters[environment].beSubscriptionId }}
        container: ${{ parameters.container }}
        destroyMode: ${{ parameters.destroyMode }}
        destroyModeLocal: ${{ parameters.destroyModeLocal }}
        poolName: ${{ parameters.poolName }}
        environment: ${{ environment }}
        environmentParameters: ${{ parameters.environmentParameters[environment] }}
        environmentDependsOn: ${{ parameters.environmentParameters[environment].dependsOn }}
        environmentName: ${{ parameters.environmentParameters[environment].environmentName }}
        dependsOn: ${{ parameters.dependsOn }}
        initCheckout: ${{ parameters.initCheckout }}
        stages: ${{ parameters.stages }}
        stageParameters: ${{ parameters.stageParameters }}
        terraformDirectory: ${{ parameters.terraformDirectory }}
        terraformTfVars: ${{ parameters.terraformTfVars }}
