---

parameters:
  - name: poolName
    type: string
  - name: environment
    type: string
  - name: dependsOn
    type: object
  - name: stages
    type: object
  - name: stageParameters
    type: object

stages:

  - ${{ each stage in parameters.stages }}:
    - template: ../stages/terraform-run-stage.yml
      parameters:
        poolName: ${{ parameters.poolName }}
        stageName: ${{ parameters.stageParameters[stage].stageName }}
        environmentName: ${{ parameters.environment }}
        condition: ${{ parameters.stageParameters[stage].condition }}
        parentDependsOn: ${{ parameters.dependsOn }}
        dependsOn: ${{ parameters.stageParameters[stage].dependsOn }}
