---

parameters:
  - name: azureSubscription
    type: string
  - name: container
    type: string
  - name: poolName
    type: string
  - name: dependsOn
    type: object
  - name: initCheckout
    type: object
  - name: parentDependsOn
    type: object
  - name: environment
    type: string
  - name: environmentName
    type: string
  - name: environmentDependsOn
    type: object
  - name: condition
    type: string
  - name: stage
    type: string
  - name: stageName
    type: string
  - name: terraformDirectory
    type: string
  - name: terraformTfVars
    type: object


stages:
  - stage: ${{ parameters.environment }}_${{ parameters.stageName }}
    # displayName: upper(parameters.targetEnvironmentName)
    pool:
      name: ${{ parameters.poolName }}
    dependsOn:
      - ${{ each depParent in parameters.parentDependsOn }}:
        - ${{ depParent }}
      - ${{ each depEnv in parameters.environmentDependsOn }}:
        - ${{ each dep in parameters.dependsOn }}:
          - ${{ depEnv }}_${{ dep }}
      - ${{ each dep in parameters.dependsOn }}:
        - ${{ parameters.environmentName }}_${{ dep }}
    condition: ${{ parameters.condition }}
    jobs:
    - ${{ if eq(parameters['stage'], 'init_plan') }}:
      - template: ../jobs/init_plan.yml
        parameters:
          azureSubscription: ${{ parameters.azureSubscription }}
          container: ${{ parameters.container }}
          checkout: ${{ parameters.initCheckout }}
          environmentName: ${{ parameters.environmentName }}
          poolName: ${{ parameters.poolName }}
          terraformDirectory: ${{ parameters.terraformDirectory }}
          terraformTfVars: ${{ parameters.terraformTfVars }}
    - ${{ if eq(parameters['stage'], 'apply') }}:
      - template: ../jobs/apply.yml
        parameters:
          azureSubscription: ${{ parameters.azureSubscription }}
          container: ${{ parameters.container }}
          environmentName: ${{ parameters.environmentName }}
          poolName: ${{ parameters.poolName }}
          terraformDirectory: ${{ parameters.terraformDirectory }}
    - ${{ if eq(parameters['stage'], 'destroy') }}:
      - template: ../jobs/destroy.yml
        parameters:
          azureSubscription: ${{ parameters.azureSubscription }}
          poolName: ${{ parameters.poolName }}
          environmentName: ${{ parameters.environmentName }}

    # dependsOn:
    #   - ${{ each depParent in parameters.parentDependsOn }}:
    #     - ${{ depParent }}
    #   - ${{ each dep in parameters.dependsOn }}:
    #     - ${{ each depEnv in parameters.environmentDependsOn }}:
    #       - ${{ depEnv }}_${{ dep }}
    #     - ${{ parameters.environmentName }}_${{ dep }}