---

parameters:
  - name: container
    type: string
  - name: poolName
    type: string
  - name: environments
    type: object
  - name: environmentParameters
    type: object
  - name: dependsOn
    type: object
  - name: stages
    type: object
  - name: stageParameters
    type: object
  - name: terraformDirectory
    type: string
  - name: terraformTfVars
    type: object

stages:

  - ${{ each environment in parameters.environments }}:
    - template: ../stages/terraform-stages.yml
      parameters:
        container: ${{ parameters.container }}
        poolName: ${{ parameters.poolName }}
        environment: ${{ environment }}
        environmentDependsOn: ${{ parameters.environmentParameters[environment].dependsOn }}
        environmentName: ${{ parameters.environmentParameters[environment].environmentName }}
        dependsOn: ${{ parameters.dependsOn }}
        stages: ${{ parameters.stages }}
        stageParameters: ${{ parameters.stageParameters }}
        terraformDirectory: ${{ parameters.terraformDirectory }}
        terraformTfVars: ${{ parameters.terraformTfVars }}
