---

parameters:
  - name: poolName
    type: string
  - name: dependsOn
    type: object
  - name: parentDependsOn
    type: object
  - name: environment
    type: string
  - name: environmentName
    type: string
  - name: environmentDependsOn
    type: object
  - name: condition
    type: string
  - name: stage
    type: string
  - name: stageName
    type: string


stages:
  - stage: ${{ parameters.environment }}_${{ parameters.stageName }}
    # displayName: upper(parameters.targetEnvironmentName)
    # dependsOn: ${{ parameters.dependsOn }}
    pool:
      name: ${{ parameters.poolName }}
    dependsOn:
      - ${{ each depParent in parameters.parentDependsOn }}:
        - ${{ depParent }}
      - ${{ each dep in parameters.dependsOn }}:
        - ${{ each depEnv in parameters.environmentDependsOn }}:
          - ${{ depEnv }}_${{ dep }}
        - ${{ parameters.environmentName }}_${{ dep }}
    condition: ${{ parameters.condition }}
    jobs:
    - ${{ if eq(parameters['stage'], 'init') }}:
      - template: ../jobs/init.yml
    - ${{ if eq(parameters['stage'], 'plan') }}:
      - template: ../jobs/plan.yml
    - ${{ if eq(parameters['stage'], 'apply') }}:
      - template: ../jobs/apply.yml
      # ${{ elseif eq(parameters['stage'], 'plan') }}:
      #   - template: ../jobs/plan.yml
      # ${{ elseif eq(parameters['stage'], 'apply') }}:
      #   - template: ../jobs/apply.yml
      # - template: ../jobs/init.yml

      # - ${{ if eq(parameters['stage'], 'init') }}:
      #     - template: ../jobs/init.yml
      #   ${{ elseif eq(parameters['stage'], 'plan') }}:
      #     - template: ../jobs/plan.yml
      #   ${{ elseif eq(parameters['stage'], 'apply') }}:
      #     - template: ../jobs/apply.yml
