---

name: "application"

trigger: none

resources:
  pipelines:
  - pipeline: application
    source: terraform
    trigger: true

variables:
- group: build
- name: serviceConnection
  value: "azure-ai-demo"
- name: acrName
  value: "azureaidemo"
- name: DOCKER_BUILDKIT
  value: 1

pool:
  name: 'vmss-bootstrap-pool'

stages:

- stage: app
  pool:
    name: 'vmss-bootstrap-pool'

  jobs:
  - job: build
    workspace:
      clean: all
    displayName: "Build and push container"
    continueOnError: false
    steps:

      - checkout: self

      - checkout: git://$(project)/ai-demo-src

      - script: |
          env
          nslookup $(acrName).azurecr.io || echo "nslookup failed"
        displayName: Debug

      - script: |
          set -e
          az login --service-principal -u $(serviceprincipalid) -p $(serviceprincipalkey) --tenant $(azurerm_spn_tenantid)
          az acr login -n $(acrName) --subscription $(azurerm_subscription_id)
        displayName: Login

      - script: |
          set -e
          docker build -t "$(acrName).azurecr.io/azureaidemo/azureaidemo:latest" .
          docker push "$(acrName).azurecr.io/azureaidemo/azureaidemo:latest" 
        displayName: Docker build and push
        workingDirectory: '$(System.DefaultWorkingDirectory)/ai-demo-src/src'
