---

name: "application"

resources:
  pipelines:
  - pipeline: application
    source: terraform
    trigger: true

variables:
- group: build
- name: DOCKER_BUILDKIT
  value: 1

pool:
  name: 'vmss-bootstrap-pool'

stages:

- stage: app

  jobs:
  - job: build
    workspace:
      clean: all
    displayName: "Build and push container"
    continueOnError: false
    steps:

      - checkout: self

      - checkout: git://$(project)/ai-demo-src

      - script: |
          env
        displayName: Debug

      - script: |
          set -e
          az login --service-principal -u $(serviceprincipalid) -p $(serviceprincipalkey) --tenant $(azurerm_spn_tenantid)
          acr_name=$(az acr list --resource-group $(resource_group) --query "[0].name" -o tsv)
          printf "ACR name: %s\n" "$acr_name"
          az acr login -n "$acr_name" --subscription $(azurerm_subscription_id)
          echo "##vso[task.setvariable variable=ACR]$acr_name"
        displayName: Login

      - script: |
          set -e
          docker build -t "${ACR}.azurecr.io/azureaidemo/azureaidemo:latest" .
          docker push "${ACR}.azurecr.io/azureaidemo/azureaidemo:latest"
        displayName: Docker build and push
        workingDirectory: '$(System.DefaultWorkingDirectory)/ai-demo-src/src'
